import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: "#f0faf4",
          100: "#d1f2e0",
          200: "#a3e5c1",
          300: "#6fd49a",
          400: "#3eba76",
          500: "#1F8A4D",
          600: "#1a7341",
          700: "#155c34",
          800: "#104628",
          900: "#0b301c",
          950: "#061a10",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          50: "#fefaed",
          100: "#fdf3cc",
          200: "#fbe799",
          300: "#f9db66",
          400: "#F8CC58",
          500: "#E4B155",
          600: "#c99a3d",
          700: "#a67d2e",
          800: "#836220",
          900: "#604714",
          950: "#3d2d0a",
          gold: "#F8CC58",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        bank: {
          50: "#f0faf4",
          100: "#d1f2e0",
          200: "#a3e5c1",
          300: "#6fd49a",
          400: "#3eba76",
          500: "#1F8A4D",
          600: "#1a7341",
          700: "#155c34",
          800: "#104628",
          900: "#0b301c",
          950: "#061a10",
        },
        success: {
          DEFAULT: "#1F8A4D",
          light: "#2BA85E",
          dark: "#176B3D",
        },
        warning: {
          DEFAULT: "#F8CC58",
          light: "#fbe799",
          dark: "#E4B155",
        },
        error: {
          DEFAULT: "#dc2626",
          light: "#ef4444",
          dark: "#b91c1c",
        },
        navy: {
          50: "#F7F7F7",
          100: "#E8E8E8",
          200: "#D1D1D1",
          300: "#B0B0B0",
          400: "#8E8E8E",
          500: "#6B6B6B",
          600: "#565656",
          700: "#3F3F3F",
          800: "#2D2D2D",
          900: "#1A1918",
          950: "#0D0C0B",
        },
      },
      fontFamily: {
        sans: [
          "Inter",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Oxygen",
          "Ubuntu",
          "sans-serif",
        ],
        display: ["Plus Jakarta Sans", "Inter", "sans-serif"],
        mono: ["JetBrains Mono", "Fira Code", "monospace"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "1rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
      },
      boxShadow: {
        "bank-sm": "0 1px 2px 0 rgba(0, 0, 0, 0.05), 0 1px 3px 0 rgba(0, 0, 0, 0.1)",
        "bank": "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)",
        "bank-md": "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1)",
        "bank-lg": "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)",
        "bank-xl": "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
        "gold": "0 4px 14px 0 rgba(248, 204, 88, 0.39)",
        "gold-lg": "0 10px 28px 0 rgba(248, 204, 88, 0.45)",
        "inner-glow": "inset 0 1px 0 0 rgba(255, 255, 255, 0.1)",
        "glass": "0 8px 32px 0 rgba(31, 138, 77, 0.15)",
        "glass-dark": "0 8px 32px 0 rgba(0, 0, 0, 0.3)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-down": {
          from: { opacity: "0", transform: "translateY(-20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.95)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(31, 138, 77, 0.4)" },
          "50%": { boxShadow: "0 0 0 10px rgba(31, 138, 77, 0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "gold-pulse": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(248, 204, 88, 0.4)" },
          "50%": { boxShadow: "0 0 0 12px rgba(248, 204, 88, 0)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-6px)" },
        },
        "slide-in-right": {
          from: { opacity: "0", transform: "translateX(20px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        "slide-in-left": {
          from: { opacity: "0", transform: "translateX(-20px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "slide-up": "slide-up 0.4s ease-out",
        "slide-down": "slide-down 0.4s ease-out",
        "scale-in": "scale-in 0.2s ease-out",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        shimmer: "shimmer 2s linear infinite",
        "gold-pulse": "gold-pulse 2s ease-in-out infinite",
        float: "float 3s ease-in-out infinite",
        "slide-in-right": "slide-in-right 0.3s ease-out",
        "slide-in-left": "slide-in-left 0.3s ease-out",
      },
      backgroundImage: {
        "bank-gradient": "linear-gradient(135deg, #1F8A4D 0%, #176B3D 100%)",
        "bank-gradient-light": "linear-gradient(135deg, #2BA85E 0%, #1F8A4D 100%)",
        "gold-gradient": "linear-gradient(135deg, #F8CC58 0%, #E4B155 100%)",
        "hero-gradient": "linear-gradient(135deg, #1A1918 0%, #1F8A4D 50%, #176B3D 100%)",
        "card-gradient": "linear-gradient(180deg, rgba(255,255,255,1) 0%, rgba(247,247,247,1) 100%)",
        "dark-gradient": "linear-gradient(180deg, #1A1918 0%, #252423 100%)",
        "surface-gradient": "linear-gradient(135deg, #F7F7F7 0%, #EBD6A3 10%)",
      },
      backdropBlur: {
        xs: "2px",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
