"use client";

import { createContext, useContext, useEffect, useState, type ReactNode } from "react";
import { useTheme } from "next-themes";

type Language = "en" | "so" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    customers: "Customers",
    employees: "Employees",
    accounts: "Accounts",
    transactions: "Transactions",
    loans: "Loans",
    reports: "Reports",
    audit_logs: "Audit Logs",
    settings: "Settings",
    notifications: "Notifications",
    profile: "Profile",
    announcements: "Announcements",
    login: "Login",
    register: "Register",
    logout: "Logout",
    search: "Search",
    filter: "Filter",
    export: "Export",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    view: "View",
    create: "Create",
    update: "Update",
    confirm: "Confirm",
    total_balance: "Total Balance",
    total_users: "Total Users",
    total_accounts: "Total Accounts",
    total_transactions: "Total Transactions",
    online_users: "Online Users",
    pending_loans: "Pending Loans",
    deposits: "Deposits",
    pending_deposits: "Pending Deposits",
    approve_deposit: "Approve Deposit",
    reject_deposit: "Reject Deposit",
    deposit_request: "Deposit Request",
    deposit_pending_approval: "Deposit pending approval",
    withdrawals: "Withdrawals",
    transfers: "Transfers",
    recent_activity: "Recent Activity",
    welcome: "Welcome",
    offline_mode: "Offline Mode",
    syncing: "Syncing...",
    sync_complete: "Sync Complete",
    no_internet: "No Internet Connection",
    pending_sync: "Pending Sync",
    daily_report: "Daily Report",
    monthly_report: "Monthly Report",
    analytics: "Analytics",
    transfer_fee: "Transfer Fee",
    min_balance: "Minimum Balance",
    max_transfer: "Maximum Transfer",
    interest_rate: "Interest Rate",
    bank_name: "Bank Name",
    currency: "Currency",
    backup_restore: "Backup & Restore",
    branch_management: "Branch Management",
    system_settings: "System Settings",
    maintenance_mode: "Maintenance Mode",
    support_email: "Support Email",
    support_phone: "Support Phone",
    deposit_money: "Deposit Money",
    withdraw_money: "Withdraw Money",
    transfer_money: "Transfer Money",
    apply_loan: "Apply for Loan",
    repay_loan: "Repay Loan",
    download_statement: "Download Statement",
    view_balance: "View Balance",
    transaction_history: "Transaction History",
    update_profile: "Update Profile",
    change_password: "Change Password",
    forgot_password: "Forgot Password",
    reset_password: "Reset Password",
    email_verification: "Email Verification",
    account_balance: "Account Balance",
    loan_status: "Loan Status",
    customer_portal: "Customer Portal",
    admin_panel: "Admin Panel",
    employee_panel: "Employee Panel",
    users: "Users",
    main: "Main",
    banking: "Banking",
    management: "Management",
    system: "System",
    other: "Other",
    language: "Language",
    welcome_back: "Welcome back",
    recent_transactions: "Recent Transactions",
    quick_actions: "Quick Actions",
    view_all: "View All",
    no_data: "No data available",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Information",
    confirm_delete: "Are you sure you want to delete?",
    create_new: "Create New",
    edit_item: "Edit Item",
    delete_item: "Delete Item",
    save_changes: "Save Changes",
    submit: "Submit",
    back: "Back",
    next: "Next",
    previous: "Previous",
    search_placeholder: "Search...",
    no_results: "No results found",
    showing: "Showing",
    of: "of",
    items: "items",
    actions: "Actions",
    status: "Status",
    date: "Date",
    amount: "Amount",
    description: "Description",
    type: "Type",
    name: "Name",
    email: "Email",
    phone: "Phone",
    address: "Address",
    city: "City",
    country: "Country",
    account_number: "Account Number",
    balance: "Balance",
    account_type: "Account Type",
    created: "Created",
    updated: "Updated",
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    completed: "Completed",
    cancelled: "Cancelled",
    all: "All",
    none: "None",
    select: "Select",
    clear: "Clear",
    apply: "Apply",
    reset: "Reset",
    import: "Import",
    download: "Download",
    upload: "Upload",
    print: "Print",
    refresh: "Refresh",
    close: "Close",
    open: "Open",
    show: "Show",
    hide: "Hide",
    more: "More",
    less: "Less",
    summary: "Summary",
    details: "Details",
    security: "Security",
    restore: "Restore",
  },
  so: {
    dashboard: "Mashruul",
    customers: "Macaamiisha",
    employees: "Shaqaalaha",
    accounts: "Xisaabaadka",
    transactions: "Dhaqdhaqaaqa",
    loans: "Deymaha",
    reports: "Warbixinno",
    audit_logs: "Diiwaanka Hubinta",
    settings: "Dejinta",
    notifications: "Ogeysiisyada",
    profile: "Profaylka",
    announcements: "Ogeysiisyada",
    login: "Gal",
    register: "Diiwaan Geli",
    logout: "Ka bax",
    search: "Raadi",
    filter: "Shaandhayn",
    export: "Soo Saar",
    save: "Kaydi",
    cancel: "Jooji",
    delete: "Tirtir",
    edit: "Wax Ka Bedel",
    view: "Eeg",
    create: "Samee",
    update: "Cusbooneysii",
    confirm: "Xaqiiji",
    total_balance: "Wadarta Hantida",
    total_users: "Wadarta Isticmaalayaasha",
    total_accounts: "Wadarta Xisaabaadka",
    total_transactions: "Wadarta Dhaqdhaqaaqa",
    online_users: "Isticmaalayaasha Online",
    pending_loans: "Deymaha Sugaya",
    deposits: "Dhigaalada",
    pending_deposits: "Dhigaalada Sugaya",
    approve_deposit: "Aqbal Dhigaal",
    reject_deposit: "Diid Dhigaal",
    deposit_request: "Codsi Dhigaal",
    deposit_pending_approval: "Dhigaalku waxa uu sugayaa aqbalaad",
    withdrawals: "Soo Celinta",
    transfers: "Ku Wareejinta",
    recent_activity: "Hawsha Dambe",
    welcome: "Soo dhawoow",
    offline_mode: "Habka Offline",
    syncing: "Isku xiraya...",
    sync_complete: "Isku xirid Dhammaatay",
    no_internet: "Internet La'aan",
    pending_sync: "Isku xirid Sugaysa",
    daily_report: "Warbixinta Maalinta",
    monthly_report: "Warbixinta Bishii",
    analytics: "Falanqaynta",
    transfer_fee: "Kharashka Wareejinta",
    min_balance: "Hantida Ugu Yar",
    max_transfer: "Wareejinta Ugu Badan",
    interest_rate: "Heerka Faaidada",
    bank_name: "Magaca Bangiga",
    currency: "Lacagta",
    backup_restore: "Kaydinta & Soo Celinta",
    branch_management: "Maamulka Laanta",
    system_settings: "Dejinta Nidaamka",
    maintenance_mode: "Habka Dayactirka",
    support_email: "Email Taageero",
    support_phone: "Telefoon Taageero",
    deposit_money: "Dhig Lacag",
    withdraw_money: "Kaqi Lacag",
    transfer_money: "Ku Wareeji Lacag",
    apply_loan: "Codsii Deyn",
    repay_loan: "Bixi Deyn",
    download_statement: "Soodejii Warbixinta",
    view_balance: "Eeg Hantida",
    transaction_history: "Taariikhda Dhaqdhaqaaqa",
    update_profile: "Cusbooneysii Profaylka",
    change_password: "Bedel Furaha",
    forgot_password: "Illoobay Furaha",
    reset_password: "Dib U Deji Furaha",
    email_verification: "Xaqiijinta Email",
    account_balance: "Hantida Xisaabta",
    loan_status: "Xaaladda Deynta",
    customer_portal: "Albaabka Macaamiisha",
    admin_panel: "Kontaroolka Maamulaha",
    employee_panel: "Kontaroolka Shaqaalaha",
    users: "Isticmaalayaasha",
    main: "Ugu Weyn",
    banking: "Bangiga",
    management: "Maamulka",
    system: "Nidaamka",
    other: "Kale",
    language: "Luqadda",
    welcome_back: "Ku soo dhawoow mar labaad",
    recent_transactions: "Dhaqdhaqaaqa Dambe",
    quick_actions: "Ficilada Degdega",
    view_all: "Eeg Dhammaan",
    no_data: "Xog la'aan",
    loading: "Soo raraya...",
    error: "Khalad",
    success: "Guul",
    warning: "Digniin",
    info: "Macluumaad",
    confirm_delete: "Ma hubtaa inaad tirtirto?",
    create_new: "Samee Cusub",
    edit_item: "Wax Ka Bedel Item",
    delete_item: "Tirtir Item",
    save_changes: "Kaydi Isbedelada",
    submit: "Gudbi",
    back: "Dib U Noqo",
    next: "Xiga",
    previous: "Hore",
    search_placeholder: "Raadi...",
    no_results: "Natiijooyin lama helin",
    showing: "Muujinaya",
    of: "ka mid ah",
    items: "shay",
    actions: "Ficilada",
    status: "Xaaladda",
    date: "Taariikhda",
    amount: "Lacagta",
    description: "Faahfaahin",
    type: "Nooc",
    name: "Magac",
    email: "Email",
    phone: "Telefoon",
    address: "Cinwaanka",
    city: "Magalada",
    country: "Wadanka",
    account_number: "Lambarka Xisaabta",
    balance: "Hantida",
    account_type: "Nooca Xisaabta",
    created: "La sameeyay",
    updated: "La cusbooneysiiyay",
    active: "Firfircoon",
    inactive: "An-firfircoon",
    pending: "Sugaysa",
    approved: "La aqbalay",
    rejected: "La diiday",
    completed: "Dhammaatay",
    cancelled: "La joojiyay",
    all: "Dhammaan",
    none: "Midna",
    select: "Dooro",
    clear: "Tirtir",
    apply: "Codsii",
    reset: "Dib U Deji",
    import: "Soo Dhoofi",
    download: "Soo Deji",
    upload: "Soo Rar",
    print: "Daabac",
    refresh: "Cusbooneysii",
    close: "Xir",
    open: "Fur",
    show: "Muujii",
    hide: "Qari",
    more: "Wax Badan",
    less: "Wax Yar",
    summary: "Kooban",
    details: "Faahfaahin",
    security: "Amniga",
    restore: "Soo Celinta",
  },
  ar: {
    dashboard: "لوحة التحكم",
    customers: "العملاء",
    employees: "الموظفون",
    accounts: "الحسابات",
    transactions: "المعاملات",
    loans: "القروض",
    reports: "التقارير",
    audit_logs: "سجلات التدقيق",
    settings: "الإعدادات",
    notifications: "الإشعارات",
    profile: "الملف الشخصي",
    announcements: "الإعلانات",
    login: "تسجيل الدخول",
    register: "التسجيل",
    logout: "تسجيل الخروج",
    search: "بحث",
    filter: "تصفية",
    export: "تصدير",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    view: "عرض",
    create: "إنشاء",
    update: "تحديث",
    confirm: "تأكيد",
    total_balance: "الرصيد الإجمالي",
    total_users: "إجمالي المستخدمين",
    total_accounts: "إجمالي الحسابات",
    total_transactions: "إجمالي المعاملات",
    online_users: "المستخدمون المتصلون",
    pending_loans: "القروض المعلقة",
    deposits: "الإيداعات",
    pending_deposits: "الإيداعات المعلقة",
    approve_deposit: "الموافقة على الإيداع",
    reject_deposit: "رفض الإيداع",
    deposit_request: "طلب إيداع",
    deposit_pending_approval: "الإيداع في انتظار الموافقة",
    withdrawals: "السحوبات",
    transfers: "التحويلات",
    recent_activity: "النشاط الأخير",
    welcome: "مرحباً",
    offline_mode: "وضع عدم الاتصال",
    syncing: "جاري المزامنة...",
    sync_complete: "اكتملت المزامنة",
    no_internet: "لا يوجد اتصال بالإنترنت",
    pending_sync: "معلق المزامنة",
    daily_report: "التقرير اليومي",
    monthly_report: "التقرير الشهري",
    analytics: "التحليلات",
    transfer_fee: "رسوم التحويل",
    min_balance: "الحد الأدنى للرصيد",
    max_transfer: "الحد الأقصى للتحويل",
    interest_rate: "سعر الفائدة",
    bank_name: "اسم البنك",
    currency: "العملة",
    backup_restore: "النسخ الاحتياطي والاستعادة",
    branch_management: "إدارة الفروع",
    system_settings: "إعدادات النظام",
    maintenance_mode: "وضع الصيانة",
    support_email: "بريد الدعم",
    support_phone: "هاتف الدعم",
    deposit_money: "إيداع أموال",
    withdraw_money: "سحب أموال",
    transfer_money: "تحويل أموال",
    apply_loan: "تقديم طلب قرض",
    repay_loan: "سداد القرض",
    download_statement: "تحميل كشف الحساب",
    view_balance: "عرض الرصيد",
    transaction_history: "سجل المعاملات",
    update_profile: "تحديث الملف الشخصي",
    change_password: "تغيير كلمة المرور",
    forgot_password: "نسيت كلمة المرور",
    reset_password: "إعادة تعيين كلمة المرور",
    email_verification: "التحقق من البريد الإلكتروني",
    account_balance: "رصيد الحساب",
    loan_status: "حالة القرض",
    customer_portal: "بوابة العميل",
    admin_panel: "لوحة الإدارة",
    employee_panel: "لوحة الموظفين",
    users: "المستخدمون",
    main: "الرئيسية",
    banking: "الخدمات المصرفية",
    management: "الإدارة",
    system: "النظام",
    other: "أخرى",
    language: "اللغة",
    welcome_back: "مرحباً بعودتك",
    recent_transactions: "المعاملات الأخيرة",
    quick_actions: "إجراءات سريعة",
    view_all: "عرض الكل",
    no_data: "لا تتوفر بيانات",
    loading: "جاري التحميل...",
    error: "خطأ",
    success: "نجاح",
    warning: "تحذير",
    info: "معلومات",
    confirm_delete: "هل أنت متأكد من الحذف؟",
    create_new: "إنشاء جديد",
    edit_item: "تعديل العنصر",
    delete_item: "حذف العنصر",
    save_changes: "حفظ التغييرات",
    submit: "إرسال",
    back: "رجوع",
    next: "التالي",
    previous: "السابق",
    search_placeholder: "بحث...",
    no_results: "لم يتم العثور على نتائج",
    showing: "عرض",
    of: "من",
    items: "عناصر",
    actions: "إجراءات",
    status: "الحالة",
    date: "التاريخ",
    amount: "المبلغ",
    description: "الوصف",
    type: "النوع",
    name: "الاسم",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    address: "العنوان",
    city: "المدينة",
    country: "الدولة",
    account_number: "رقم الحساب",
    balance: "الرصيد",
    account_type: "نوع الحساب",
    created: "تاريخ الإنشاء",
    updated: "تاريخ التحديث",
    active: "نشط",
    inactive: "غير نشط",
    pending: "معلق",
    approved: "موافق عليه",
    rejected: "مرفوض",
    completed: "مكتمل",
    cancelled: "ملغي",
    all: "الكل",
    none: "لا شيء",
    select: "اختيار",
    clear: "مسح",
    apply: "تطبيق",
    reset: "إعادة تعيين",
    import: "استيراد",
    download: "تنزيل",
    upload: "رفع",
    print: "طباعة",
    refresh: "تحديث",
    close: "إغلاق",
    open: "فتح",
    show: "إظهار",
    hide: "إخفاء",
    more: "المزيد",
    less: "الأقل",
    summary: "ملخص",
    details: "تفاصيل",
    security: "الأمان",
    restore: "استعادة",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const stored = localStorage.getItem("language") as Language;
    if (stored && translations[stored]) {
      setLanguageState(stored);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
