"use client";

import { createContext, useContext, useEffect, useState, type ReactNode } from "react";
import { useTheme } from "next-themes";

type Language = "en" | "so" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    customers: "Customers",
    employees: "Employees",
    accounts: "Accounts",
    transactions: "Transactions",
    loans: "Loans",
    reports: "Reports",
    audit_logs: "Audit Logs",
    settings: "Settings",
    notifications: "Notifications",
    profile: "Profile",
    announcements: "Announcements",
    credentials: "Credentials",
    login: "Login",
    register: "Register",
    logout: "Logout",
    search: "Search",
    filter: "Filter",
    export: "Export",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    view: "View",
    create: "Create",
    update: "Update",
    confirm: "Confirm",
    total_balance: "Total Balance",
    total_users: "Total Users",
    total_accounts: "Total Accounts",
    total_transactions: "Total Transactions",
    online_users: "Online Users",
    pending_loans: "Pending Loans",
    deposits: "Deposits",
    pending_deposits: "Pending Deposits",
    approve_deposit: "Approve Deposit",
    reject_deposit: "Reject Deposit",
    deposit_request: "Deposit Request",
    deposit_pending_approval: "Deposit pending approval",
    withdrawals: "Withdrawals",
    transfers: "Transfers",
    recent_activity: "Recent Activity",
    welcome: "Welcome",
    offline_mode: "Offline Mode",
    syncing: "Syncing...",
    sync_complete: "Sync Complete",
    no_internet: "No Internet Connection",
    pending_sync: "Pending Sync",
    daily_report: "Daily Report",
    monthly_report: "Monthly Report",
    analytics: "Analytics",
    transfer_fee: "Transfer Fee",
    min_balance: "Minimum Balance",
    max_transfer: "Maximum Transfer",
    interest_rate: "Interest Rate",
    bank_name: "Bank Name",
    currency: "Currency",
    backup_restore: "Backup & Restore",
    branch_management: "Branch Management",
    system_settings: "System Settings",
    maintenance_mode: "Maintenance Mode",
    support_email: "Support Email",
    support_phone: "Support Phone",
    deposit_money: "Deposit Money",
    withdraw_money: "Withdraw Money",
    transfer_money: "Transfer Money",
    apply_loan: "Apply for Loan",
    repay_loan: "Repay Loan",
    download_statement: "Download Statement",
    view_balance: "View Balance",
    transaction_history: "Transaction History",
    update_profile: "Update Profile",
    change_password: "Change Password",
    forgot_password: "Forgot Password",
    reset_password: "Reset Password",
    email_verification: "Email Verification",
    account_balance: "Account Balance",
    loan_status: "Loan Status",
    customer_portal: "Customer Portal",
    admin_panel: "Admin Panel",
    employee_panel: "Employee Panel",
    users: "Users",
    main: "Main",
    banking: "Banking",
    management: "Management",
    system: "System",
    other: "Other",
    language: "Language",
    welcome_back: "Welcome back",
    recent_transactions: "Recent Transactions",
    quick_actions: "Quick Actions",
    view_all: "View All",
    no_data: "No data available",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Information",
    confirm_delete: "Are you sure you want to delete?",
    create_new: "Create New",
    edit_item: "Edit Item",
    delete_item: "Delete Item",
    save_changes: "Save Changes",
    submit: "Submit",
    back: "Back",
    next: "Next",
    previous: "Previous",
    search_placeholder: "Search...",
    no_results: "No results found",
    showing: "Showing",
    of: "of",
    items: "items",
    actions: "Actions",
    status: "Status",
    date: "Date",
    amount: "Amount",
    description: "Description",
    type: "Type",
    name: "Name",
    email: "Email",
    phone: "Phone",
    address: "Address",
    city: "City",
    country: "Country",
    account_number: "Account Number",
    balance: "Balance",
    account_type: "Account Type",
    created: "Created",
    updated: "Updated",
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    completed: "Completed",
    cancelled: "Cancelled",
    all: "All",
    none: "None",
    select: "Select",
    clear: "Clear",
    apply: "Apply",
    reset: "Reset",
    import: "Import",
    download: "Download",
    upload: "Upload",
    print: "Print",
    refresh: "Refresh",
    close: "Close",
    open: "Open",
    show: "Show",
    hide: "Hide",
    more: "More",
    less: "Less",
    summary: "Summary",
    details: "Details",
    security: "Security",
    restore: "Restore",
    // Landing page
    secure_banking: "Secure Banking Platform",
    modern_banking: "Modern Banking",
    management_system: "Management System",
    landing_desc: "Nidaamka maamulka bank-ka ee casriga ah - maamulka koontoyinka, dhaqdhaqaaqa lacagaha, warbixinta, iyo wax kasta oo ku saabsan maaliyadaada.",
    start_free_account: "Start Free Account",
    sign_in_dashboard: "Sign In to Dashboard",
    ssl_encrypted: "SSL Encrypted",
    two_fa_security: "2FA Security",
    pci_compliant: "PCI Compliant",
    customers_label: "Customers",
    total_balance_label: "Total Balance",
    transactions_label: "Transactions",
    uptime_label: "Uptime",
    powerful_features: "Powerful Features",
    everything_you_need: "Everything You Need",
    features_desc: "Dhammaan adeegyada aad u baahan tahay si aad u maamusho maaliyadaada si fudud oo ammaan ah.",
    account_management: "Account Management",
    account_management_desc: "Maamulka koontadaada - samee koontooyin cusub, eeg balanska, iyo maamulka noocyada kala duwan.",
    learn_more: "Learn more",
    transactions_feature: "Transactions",
    transactions_desc: "Dhaqdhaqaaqa lacagaha - lacag dhig, lacag ka soo bixi, iyo wax kasta oo ku saabsan transactions.",
    fund_transfers: "Fund Transfers",
    fund_transfers_desc: "Dirida lacagaha si dhakhso ah oo ammaan ah - gudaha iyo dibaddaba.",
    loan_services: "Loan Services",
    loan_services_desc: "Adeegyada deynta - codso deyn, eeg xaalada deynta, iyo lacag bixinta.",
    reports_analytics: "Reports & Analytics",
    reports_desc: "Warbixinta iyo falanqaynta - eeg macluumaadka muhiimka ah iyo warbixinnada maalinlaha.",
    employee_management: "Employee Management",
    employee_desc: "Maamulka shaqaalaha - ku dar, wax ka bedel, eeg xogta shaqaalaha.",
    dashboard_preview: "Dashboard Preview",
    your_financial_dashboard: "Your Financial Dashboard",
    dashboard_preview_desc: "Eeg sida dashboard-kaagu uu u ekaan doono - dhammaan macluumaadka muhiimka ah hal meel.",
    good_morning: "Good morning",
    total_balance_dash: "Total Balance",
    customers_dash: "Customers",
    transactions_dash: "Transactions",
    pending_loans_dash: "Pending Loans",
    monthly_transactions: "Monthly Transactions",
    deposits_vs_withdrawals: "Deposits vs Withdrawals",
    deposits_label: "Deposits",
    withdrawals_label: "Withdrawals",
    how_it_works: "How It Works",
    simple_process: "Simple Process",
    how_it_works_desc: "Saddex tallaabo oo fudud si aad u bilowdo",
    step: "Step",
    create_account: "Create Account",
    create_account_desc: "Samee koonto cusub oo free ah - waxaad u baahan tahay kaliya magaca iyo emailka.",
    login_verify: "Login & Verify",
    login_verify_desc: "Geli xogahaaga (username iyo password) si aad u gasho nidaamka.",
    access_dashboard: "Access Dashboard",
    access_dashboard_desc: "Hel dashboard-kaaga oo dhammaan adeegyada ku jiraan hal meel.",
    trusted_by_thousands: "Trusted by Thousands",
    trusted_desc: "Macaamiiladeenu waxay ku qanceen nidaamkan",
    ready_to_get_started: "Ready to Get Started?",
    ready_desc: "Bilow maamulka maaliyadaada maanta - koonto bilaash ah, wax kharash ah la'aan.",
    create_free_account: "Create Free Account",
    quick_links: "Quick Links",
    account_link: "Account",
    create_account_link: "Create Account",
    forgot_password_link: "Forgot Password",
    copyright: "© 2026 Gabiley Bank. All rights reserved.",
    testimonial_1: "Nidaamkan waa mid aad u fudud oo wax ku ool ah. Waxaan ku maamulaa ganacsadayda si dhakhso ah.",
    testimonial_2: "Waxaan jeclahay sida nidaamku uu u fudud yahay. Waxaan ku gali karaa koontayda meel kasta.",
    testimonial_3: "Adeegyada shaqaalaha waa kuwo aad u fiican. Waxaan ku maamulaa macaamiisha si fudud.",
    // Additional descriptive texts
    account_management_full: "Manage your accounts easily - create new accounts, view balances, switch between different types, and keep all your finances in one secure place.",
    transactions_full: "Fast financial transactions - deposit, withdraw, transfer, view history of all transactions, and keep track of all your money.",
    transfers_full: "Send money fast and securely - domestic and international, transfer to other banks, add mobile money, and track all transfers.",
    loans_full: "Loan services - apply for a new loan, view loan status, repay, and track interest and loan period.",
    reports_full: "Reports and analytics - view important data, daily reports, customer summaries, and track your business.",
    security_full: "Financial security - 2FA system, encrypted keys, data backup, and protection of your information.",
    employee_management_full: "Employee management - add new employees, edit data, view their work, and manage permissions and payroll.",
    customer_service_full: "Customer service - contact support, view requests, add new customers, and easily manage business relationships.",
    // Roles
    business_owner: "Business Owner",
    customer_role: "Customer",
    employee_role: "Employee",
    // Account Registration
    mother_name: "Mother's Full Name",
    id_card_image: "ID Card Image",
    account_type: "Account Type",
    savings_account: "Savings Account",
    current_account: "Current Account",
    fixed_deposit: "Fixed Deposit",
    purpose: "Purpose",
    create_account_for_customer: "Create Account for Customer",
    create_account_desc: "Create a new bank account for a customer",
    search_customer: "Search Customer",
    search_customer_placeholder: "Search by name, username, or email...",
    select_customer: "Select Customer",
    account_created_success: "Account created successfully",
    add_new_account: "Add New Account",
    existing_customer: "Existing Customer",
    new_customer: "New Customer",
    create_account: "Create Account",
    change: "Change",
    full_name_placeholder: "Enter full name",
    username_placeholder: "Choose a username",
    email_placeholder: "Enter email address",
    phone_placeholder: "Enter phone number",
    password_placeholder: "Enter password",
    confirm_password_placeholder: "Confirm password",
    mother_name_placeholder: "Enter mother's full name",
    upload_id_card: "Upload ID card (max 5MB)",
    purpose_placeholder: "Purpose of this account...",
    // Months
    jan: "Jan",
    feb: "Feb",
    mar: "Mar",
    apr: "Apr",
    may: "May",
    jun: "Jun",
    jul: "Jul",
    aug: "Aug",
    sep: "Sep",
    oct: "Oct",
    nov: "Nov",
    dec: "Dec",
    ssl_256: "256-bit SSL",
    // Top Users
    top_users: "Top Users",
    most_active_users: "Most Active Users",
    most_active_logins: "Most Active (Logins)",
    most_active_transactions: "Most Active (Transactions)",
    employee_performance: "Employee Performance",
    login_count: "Login Count",
    transaction_count: "Transaction Count",
    total_processed: "Total Processed",
    active_this_week: "Active This Week",
    active_this_month: "Active This Month",
    user_rankings: "User Rankings",
    activity_summary: "Activity Summary",
    top_accounts: "Top Accounts",
    active_users: "Active Users",
    logins_this_week: "Logins This Week",
    logins_this_month: "Logins This Month",
  },
  so: {
    dashboard: "Mashruul",
    customers: "Macaamiisha",
    employees: "Shaqaalaha",
    accounts: "Xisaabaadka",
    transactions: "Dhaqdhaqaaqa",
    loans: "Deymaha",
    reports: "Warbixinno",
    audit_logs: "Diiwaanka Hubinta",
    settings: "Dejinta",
    notifications: "Ogeysiisyada",
    profile: "Profaylka",
    announcements: "Ogeysiisyada",
    credentials: "Aqoonsiyada",
    login: "Gal",
    register: "Diiwaan Geli",
    logout: "Ka bax",
    search: "Raadi",
    filter: "Shaandhayn",
    export: "Soo Saar",
    save: "Kaydi",
    cancel: "Jooji",
    delete: "Tirtir",
    edit: "Wax Ka Bedel",
    view: "Eeg",
    create: "Samee",
    update: "Cusbooneysii",
    confirm: "Xaqiiji",
    total_balance: "Wadarta Hantida",
    total_users: "Wadarta Isticmaalayaasha",
    total_accounts: "Wadarta Xisaabaadka",
    total_transactions: "Wadarta Dhaqdhaqaaqa",
    online_users: "Isticmaalayaasha Online",
    pending_loans: "Deymaha Sugaya",
    deposits: "Dhigaalada",
    pending_deposits: "Dhigaalada Sugaya",
    approve_deposit: "Aqbal Dhigaal",
    reject_deposit: "Diid Dhigaal",
    deposit_request: "Codsi Dhigaal",
    deposit_pending_approval: "Dhigaalku waxa uu sugayaa aqbalaad",
    withdrawals: "Soo Celinta",
    transfers: "Ku Wareejinta",
    recent_activity: "Hawsha Dambe",
    welcome: "Soo dhawoow",
    offline_mode: "Habka Offline",
    syncing: "Isku xiraya...",
    sync_complete: "Isku xirid Dhammaatay",
    no_internet: "Internet La'aan",
    pending_sync: "Isku xirid Sugaysa",
    daily_report: "Warbixinta Maalinta",
    monthly_report: "Warbixinta Bishii",
    analytics: "Falanqaynta",
    transfer_fee: "Kharashka Wareejinta",
    min_balance: "Hantida Ugu Yar",
    max_transfer: "Wareejinta Ugu Badan",
    interest_rate: "Heerka Faaidada",
    bank_name: "Magaca Bangiga",
    currency: "Lacagta",
    backup_restore: "Kaydinta & Soo Celinta",
    branch_management: "Maamulka Laanta",
    system_settings: "Dejinta Nidaamka",
    maintenance_mode: "Habka Dayactirka",
    support_email: "Email Taageero",
    support_phone: "Telefoon Taageero",
    deposit_money: "Dhig Lacag",
    withdraw_money: "Kaqi Lacag",
    transfer_money: "Ku Wareeji Lacag",
    apply_loan: "Codsii Deyn",
    repay_loan: "Bixi Deyn",
    download_statement: "Soodejii Warbixinta",
    view_balance: "Eeg Hantida",
    transaction_history: "Taariikhda Dhaqdhaqaaqa",
    update_profile: "Cusbooneysii Profaylka",
    change_password: "Bedel Furaha",
    forgot_password: "Illoobay Furaha",
    reset_password: "Dib U Deji Furaha",
    email_verification: "Xaqiijinta Email",
    account_balance: "Hantida Xisaabta",
    loan_status: "Xaaladda Deynta",
    customer_portal: "Albaabka Macaamiisha",
    admin_panel: "Kontaroolka Maamulaha",
    employee_panel: "Kontaroolka Shaqaalaha",
    users: "Isticmaalayaasha",
    main: "Ugu Weyn",
    banking: "Bangiga",
    management: "Maamulka",
    system: "Nidaamka",
    other: "Kale",
    language: "Luqadda",
    welcome_back: "Ku soo dhawoow mar labaad",
    recent_transactions: "Dhaqdhaqaaqa Dambe",
    quick_actions: "Ficilada Degdega",
    view_all: "Eeg Dhammaan",
    no_data: "Xog la'aan",
    loading: "Soo raraya...",
    error: "Khalad",
    success: "Guul",
    warning: "Digniin",
    info: "Macluumaad",
    confirm_delete: "Ma hubtaa inaad tirtirto?",
    create_new: "Samee Cusub",
    edit_item: "Wax Ka Bedel Item",
    delete_item: "Tirtir Item",
    save_changes: "Kaydi Isbedelada",
    submit: "Gudbi",
    back: "Dib U Noqo",
    next: "Xiga",
    previous: "Hore",
    search_placeholder: "Raadi...",
    no_results: "Natiijooyin lama helin",
    showing: "Muujinaya",
    of: "ka mid ah",
    items: "shay",
    actions: "Ficilada",
    status: "Xaaladda",
    date: "Taariikhda",
    amount: "Lacagta",
    description: "Faahfaahin",
    type: "Nooc",
    name: "Magac",
    email: "Email",
    phone: "Telefoon",
    address: "Cinwaanka",
    city: "Magalada",
    country: "Wadanka",
    account_number: "Lambarka Xisaabta",
    balance: "Hantida",
    account_type: "Nooca Xisaabta",
    created: "La sameeyay",
    updated: "La cusbooneysiiyay",
    active: "Firfircoon",
    inactive: "An-firfircoon",
    pending: "Sugaysa",
    approved: "La aqbalay",
    rejected: "La diiday",
    completed: "Dhammaatay",
    cancelled: "La joojiyay",
    all: "Dhammaan",
    none: "Midna",
    select: "Dooro",
    clear: "Tirtir",
    apply: "Codsii",
    reset: "Dib U Deji",
    import: "Soo Dhoofi",
    download: "Soo Deji",
    upload: "Soo Rar",
    print: "Daabac",
    refresh: "Cusbooneysii",
    close: "Xir",
    open: "Fur",
    show: "Muujii",
    hide: "Qari",
    more: "Wax Badan",
    less: "Wax Yar",
    summary: "Kooban",
    details: "Faahfaahin",
    security: "Amniga",
    restore: "Soo Celinta",
    // Landing page
    secure_banking: "Nidaamka Bangiga ee Amaanka",
    modern_banking: "Bangiga Casriga ah",
    management_system: "Nidaamka Maamulka",
    landing_desc: "Nidaamka maamulka bank-ka ee casriga ah - maamulka koontoyinka, dhaqdhaqaaqa lacagaha, warbixinta, iyo wax kasta oo ku saabsan maaliyadaada.",
    start_free_account: "Bilow Koonto Bilaash ah",
    sign_in_dashboard: "Gal Dashboard-ka",
    ssl_encrypted: "SSL La Xidhiiday",
    two_fa_security: "2FA Ammaan",
    pci_compliant: "PCI La Raacay",
    customers_label: "Macaamiisha",
    total_balance_label: "Wadarta Hantida",
    transactions_label: "Dhaqdhaqaaqa",
    uptime_label: "Waqtiga",
    powerful_features: "Astaamo Awood leh",
    everything_you_need: "Wixii Dhammaan Aad U Baahan Tahay",
    features_desc: "Dhammaan adeegyada aad u baahan tahay si aad u maamusho maaliyadaada si fudud oo ammaan ah.",
    account_management: "Maamulka Koontada",
    account_management_desc: "Maamulka koontadaada - samee koontooyin cusub, eeg balanska, iyo maamulka noocyada kala duwan.",
    learn_more: "Wax Badan Ogoow",
    transactions_feature: "Dhaqdhaqaaqa",
    transactions_desc: "Dhaqdhaqaaqa lacagaha - lacag dhig, lacag ka soo bixi, iyo wax kasta oo ku saabsan transactions.",
    fund_transfers: "Dirida Lacagaha",
    fund_transfers_desc: "Dirida lacagaha si dhakhso ah oo ammaan ah - gudaha iyo dibaddaba.",
    loan_services: "Adeegyada Deynta",
    loan_services_desc: "Adeegyada deynta - codso deyn, eeg xaalada deynta, iyo lacag bixinta.",
    reports_analytics: "Warbixinno iyo Falanqayn",
    reports_desc: "Warbixinta iyo falanqaynta - eeg macluumaadka muhiimka ah iyo warbixinnada maalinlaha.",
    employee_management: "Maamulka Shaqaalaha",
    employee_desc: "Maamulka shaqaalaha - ku dar, wax ka bedel, eeg xogta shaqaalaha.",
    dashboard_preview: "Muuqaalka Dashboard-ka",
    your_financial_dashboard: "Dashboard-ka Maaliyadaada",
    dashboard_preview_desc: "Eeg sida dashboard-kaagu uu u ekaan doono - dhammaan macluumaadka muhiimka ah hal meel.",
    good_morning: "Subax wanaagsan",
    total_balance_dash: "Wadarta Hantida",
    customers_dash: "Macaamiisha",
    transactions_dash: "Dhaqdhaqaaqa",
    pending_loans_dash: "Deymaha Sugaya",
    monthly_transactions: "Dhaqdhaqaaqa Bishii",
    deposits_vs_withdrawals: "Dhigaalada vs Soo Celinta",
    deposits_label: "Dhigaalada",
    withdrawals_label: "Soo Celinta",
    how_it_works: "Sida Uu Shaqeeyo",
    simple_process: "Hab Fudud",
    how_it_works_desc: "Saddex tallaabo oo fudud si aad u bilowdo",
    step: "Tallaabo",
    create_account: "Samee Koonto",
    create_account_desc: "Samee koonto cusub oo free ah - waxaad u baahan tahay kaliya magaca iyo emailka.",
    login_verify: "Gal & Xaqiiji",
    login_verify_desc: "Geli xogahaaga (username iyo password) si aad u gasho nidaamka.",
    access_dashboard: "Hel Dashboard-ka",
    access_dashboard_desc: "Hel dashboard-kaaga oo dhammaan adeegyada ku jiraan hal meel.",
    trusted_by_thousands: "Kumanaan Qof Ay Ku Kalsoon Yihiin",
    trusted_desc: "Macaamiiladeenu waxay ku qanceen nidaamkan",
    ready_to_get_started: "Diyaar Ma U Tahay Inaad Bilowdo?",
    ready_desc: "Bilow maamulka maaliyadaada maanta - koonto bilaash ah, wax kharash ah la'aan.",
    create_free_account: "Samee Koonto Bilaash ah",
    quick_links: "Links Degdeg ah",
    account_link: "Koonto",
    create_account_link: "Samee Koonto",
    forgot_password_link: "Illoobay Furaha",
    copyright: "© 2026 Gabiley Bank. Xuquuqda waa la xoojiyay.",
    testimonial_1: "Nidaamkan waa mid aad u fudud oo wax ku ool ah. Waxaan ku maamulaa ganacsadayda si dhakhso ah.",
    testimonial_2: "Waxaan jeclahay sida nidaamku uu u fudud yahay. Waxaan ku gali karaa koontayda meel kasta.",
    testimonial_3: "Adeegyada shaqaalaha waa kuwo aad u fiican. Waxaan ku maamulaa macaamiisha si fudud.",
    // Additional descriptive texts
    account_management_full: "Maamulka koontadaada si fudud - samee koontooyin cusub, eeg balanska, ku bedel noocyada kala duwan, oo dhamaan maaliyadaada ku hayso meel ammaan ah.",
    transactions_full: "Dhaqdhaqaaqa lacagaha si dhakhso ah - lacag dhig, lacag ka soo bixi, ku wareeji, eeg taariikhda dhammaan dhaqdhaqaaqyada, oo la soco dhammaan lacagahaaga.",
    transfers_full: "Dirida lacagaha si dhakhso ah oo ammaan ah - gudaha iyo dibaddaba, ku wareeji banksyada kale, ku dar kuwa qaadka lacagta, oo la soco dhammaan wareejimaha.",
    loans_full: "Adeegyada deynta - codso deyn cusub, eeg xaalada deynta, bixi lacagaha, oo la soco faaidada iyo waqtiga deynta.",
    reports_full: "Warbixinta iyo falanqaynta - eeg macluumaadka muhiimka ah, warbixinnada maalinlaha, ku dhawaaqida macaamiisha, oo la soco ganacsigaaga.",
    security_full: "Amniga maaliyadaada - nidaamka 2FA, furaha sirta ah, kaydinta xogta, iyo ilaalinta macluumaadkaaga.",
    employee_management_full: "Maamulka shaqaalaha - ku dar shaqaale cusub, wax ka bedel xogta, eeg shaqadooda, oo maamulka rukhsadaha iyo mushaharka.",
    customer_service_full: "Adeegyada macaamiisha - la xiriir taageero, eeg codsiyada, ku dar macaamiil cusub, oo si fudud u maamul xidhiidhada ganacsiga.",
    // Roles
    business_owner: "Milkiilaha Ganacsiga",
    customer_role: "Macmiil",
    employee_role: "Shaqaale",
    // Account Registration
    mother_name: "Magaca Hooyada",
    id_card_image: "Sawirka Kaarka Aqoonsiga",
    account_type: "Nooca Xisaabta",
    savings_account: "Xisaabta Kaydka",
    current_account: "Xisaabta Hadda",
    fixed_deposit: "Meel-dhigid Joogta ah",
    purpose: "Ujeeddo",
    create_account_for_customer: "Samee Xisaab Macmiil",
    create_account_desc: "Samee xisaab cusub macmiil",
    search_customer: "Raadi Macmiil",
    search_customer_placeholder: "Raadi magac, username, ama email...",
    select_customer: "Dooro Macmiil",
    account_created_success: "Xisaabta waa la sameeyay",
    add_new_account: "Ku Dar Xisaab Cusub",
    existing_customer: "Macmiil Jira",
    new_customer: "Macmiil Cusub",
    create_account: "Samee Xisaab",
    change: "Bedel",
    full_name_placeholder: "Geli magaca buuxa",
    username_placeholder: "Dooro username",
    email_placeholder: "Geli email address",
    phone_placeholder: "Geli lambar telefoon",
    password_placeholder: "Geli furaha",
    confirm_password_placeholder: "Xaqiiji furaha",
    mother_name_placeholder: "Geli magaca hooyada",
    upload_id_card: "Ku dar sawirka kaarka aqoonsiga (ugu badnaan 5MB)",
    purpose_placeholder: "Ujeedda xisaabtan...",
    // Months
    jan: "Jan",
    feb: "Feb",
    mar: "Mar",
    apr: "Apr",
    may: "May",
    jun: "Jun",
    jul: "Jul",
    aug: "Aug",
    sep: "Sep",
    oct: "Oct",
    nov: "Nov",
    dec: "Dec",
    ssl_256: "256-bit SSL",
    // Top Users
    top_users: "Isticmaalayaasha Ugu Sarreeya",
    most_active_users: "Isticmaalayaasha Ugu Firfircoon",
    most_active_logins: "Ugu Firfircoon (Galitaanka)",
    most_active_transactions: "Ugu Firfircoon (Dhaqdhaqaaqa)",
    employee_performance: "Waxqabadka Shaqaalaha",
    login_count: "Tirada Galitaanka",
    transaction_count: "Tirada Dhaqdhaqaaqa",
    total_processed: "Wadarta La Qabtay",
    active_this_week: "Firfircoon Toddobaadkan",
    active_this_month: "Firfircoon Bishan",
    user_rankings: "Heerka Isticmaalayaasha",
    activity_summary: "Kooban Firfircooni",
    top_accounts: "Xisaabaadka Ugu Sarreeya",
    active_users: "Isticmaalayaasha Firfircoon",
    logins_this_week: "Galitaanka Toddobaadkan",
    logins_this_month: "Galitaanka Bishan",
  },
  ar: {
    dashboard: "لوحة التحكم",
    customers: "العملاء",
    employees: "الموظفون",
    accounts: "الحسابات",
    transactions: "المعاملات",
    loans: "القروض",
    reports: "التقارير",
    audit_logs: "سجلات التدقيق",
    settings: "الإعدادات",
    notifications: "الإشعارات",
    profile: "الملف الشخصي",
    announcements: "الإعلانات",
    credentials: "بيانات الاعتماد",
    login: "تسجيل الدخول",
    register: "التسجيل",
    logout: "تسجيل الخروج",
    search: "بحث",
    filter: "تصفية",
    export: "تصدير",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    view: "عرض",
    create: "إنشاء",
    update: "تحديث",
    confirm: "تأكيد",
    total_balance: "الرصيد الإجمالي",
    total_users: "إجمالي المستخدمين",
    total_accounts: "إجمالي الحسابات",
    total_transactions: "إجمالي المعاملات",
    online_users: "المستخدمون المتصلون",
    pending_loans: "القروض المعلقة",
    deposits: "الإيداعات",
    pending_deposits: "الإيداعات المعلقة",
    approve_deposit: "الموافقة على الإيداع",
    reject_deposit: "رفض الإيداع",
    deposit_request: "طلب إيداع",
    deposit_pending_approval: "الإيداع في انتظار الموافقة",
    withdrawals: "السحوبات",
    transfers: "التحويلات",
    recent_activity: "النشاط الأخير",
    welcome: "مرحباً",
    offline_mode: "وضع عدم الاتصال",
    syncing: "جاري المزامنة...",
    sync_complete: "اكتملت المزامنة",
    no_internet: "لا يوجد اتصال بالإنترنت",
    pending_sync: "معلق المزامنة",
    daily_report: "التقرير اليومي",
    monthly_report: "التقرير الشهري",
    analytics: "التحليلات",
    transfer_fee: "رسوم التحويل",
    min_balance: "الحد الأدنى للرصيد",
    max_transfer: "الحد الأقصى للتحويل",
    interest_rate: "سعر الفائدة",
    bank_name: "اسم البنك",
    currency: "العملة",
    backup_restore: "النسخ الاحتياطي والاستعادة",
    branch_management: "إدارة الفروع",
    system_settings: "إعدادات النظام",
    maintenance_mode: "وضع الصيانة",
    support_email: "بريد الدعم",
    support_phone: "هاتف الدعم",
    deposit_money: "إيداع أموال",
    withdraw_money: "سحب أموال",
    transfer_money: "تحويل أموال",
    apply_loan: "تقديم طلب قرض",
    repay_loan: "سداد القرض",
    download_statement: "تحميل كشف الحساب",
    view_balance: "عرض الرصيد",
    transaction_history: "سجل المعاملات",
    update_profile: "تحديث الملف الشخصي",
    change_password: "تغيير كلمة المرور",
    forgot_password: "نسيت كلمة المرور",
    reset_password: "إعادة تعيين كلمة المرور",
    email_verification: "التحقق من البريد الإلكتروني",
    account_balance: "رصيد الحساب",
    loan_status: "حالة القرض",
    customer_portal: "بوابة العميل",
    admin_panel: "لوحة الإدارة",
    employee_panel: "لوحة الموظفين",
    users: "المستخدمون",
    main: "الرئيسية",
    banking: "الخدمات المصرفية",
    management: "الإدارة",
    system: "النظام",
    other: "أخرى",
    language: "اللغة",
    welcome_back: "مرحباً بعودتك",
    recent_transactions: "المعاملات الأخيرة",
    quick_actions: "إجراءات سريعة",
    view_all: "عرض الكل",
    no_data: "لا تتوفر بيانات",
    loading: "جاري التحميل...",
    error: "خطأ",
    success: "نجاح",
    warning: "تحذير",
    info: "معلومات",
    confirm_delete: "هل أنت متأكد من الحذف؟",
    create_new: "إنشاء جديد",
    edit_item: "تعديل العنصر",
    delete_item: "حذف العنصر",
    save_changes: "حفظ التغييرات",
    submit: "إرسال",
    back: "رجوع",
    next: "التالي",
    previous: "السابق",
    search_placeholder: "بحث...",
    no_results: "لم يتم العثور على نتائج",
    showing: "عرض",
    of: "من",
    items: "عناصر",
    actions: "إجراءات",
    status: "الحالة",
    date: "التاريخ",
    amount: "المبلغ",
    description: "الوصف",
    type: "النوع",
    name: "الاسم",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    address: "العنوان",
    city: "المدينة",
    country: "الدولة",
    account_number: "رقم الحساب",
    balance: "الرصيد",
    account_type: "نوع الحساب",
    created: "تاريخ الإنشاء",
    updated: "تاريخ التحديث",
    active: "نشط",
    inactive: "غير نشط",
    pending: "معلق",
    approved: "موافق عليه",
    rejected: "مرفوض",
    completed: "مكتمل",
    cancelled: "ملغي",
    all: "الكل",
    none: "لا شيء",
    select: "اختيار",
    clear: "مسح",
    apply: "تطبيق",
    reset: "إعادة تعيين",
    import: "استيراد",
    download: "تنزيل",
    upload: "رفع",
    print: "طباعة",
    refresh: "تحديث",
    close: "إغلاق",
    open: "فتح",
    show: "إظهار",
    hide: "إخفاء",
    more: "المزيد",
    less: "الأقل",
    summary: "ملخص",
    details: "تفاصيل",
    security: "الأمان",
    restore: "استعادة",
    // Landing page
    secure_banking: "منصة مصرفية آمنة",
    modern_banking: "بنك حديث",
    management_system: "نظام الإدارة",
    landing_desc: "نظام إدارة البنك الحديث - إدارة الحسابات، المعاملات المالية، التقارير، وكل ما يتعلق بأموالك.",
    start_free_account: "ابدأ حساب مجاني",
    sign_in_dashboard: "تسجيل الدخول إلى لوحة التحكم",
    ssl_encrypted: "تشفير SSL",
    two_fa_security: "أمان 2FA",
    pci_compliant: "متوافق مع PCI",
    customers_label: "العملاء",
    total_balance_label: "الرصيد الإجمالي",
    transactions_label: "المعاملات",
    uptime_label: "وقت التشغيل",
    powerful_features: "ميزات قوية",
    everything_you_need: "كل ما تحتاجه",
    features_desc: "جميع الخدمات التي تحتاجها لإدارة أموالك بسهولة وأمان.",
    account_management: "إدارة الحسابات",
    account_management_desc: "إدارة حساباتك - إنشاء حسابات جديدة، عرض الرصيد، وإدارة الأنواع المختلفة.",
    learn_more: "اعرف المزيد",
    transactions_feature: "المعاملات",
    transactions_desc: "المعاملات المالية - إيداع، سحب، وكل ما يتعلق بالمعاملات.",
    fund_transfers: "تحويل الأموال",
    fund_transfers_desc: "تحويل الأموال بسرعة وأمان - محلياً ودولياً.",
    loan_services: "خدمات القروض",
    loan_services_desc: "خدمات القروض - التقديم على قرض، متابعة حالة القرض، والسداد.",
    reports_analytics: "التقارير والتحليلات",
    reports_desc: "التقارير والتحليلات - عرض المعلومات المهمة والتقارير اليومية.",
    employee_management: "إدارة الموظفين",
    employee_desc: "إدارة الموظفين - إضافة، تعديل، وعرض بيانات الموظفين.",
    dashboard_preview: "معاينة لوحة التحكم",
    your_financial_dashboard: "لوحة التحكم المالية",
    dashboard_preview_desc: "شاهد كيف ستبدو لوحة التحكم الخاصة بك - جميع المعلومات المهمة في مكان واحد.",
    good_morning: "صباح الخير",
    total_balance_dash: "الرصيد الإجمالي",
    customers_dash: "العملاء",
    transactions_dash: "المعاملات",
    pending_loans_dash: "القروض المعلقة",
    monthly_transactions: "المعاملات الشهرية",
    deposits_vs_withdrawals: "الإيداعات مقابل السحوبات",
    deposits_label: "الإيداعات",
    withdrawals_label: "السحوبات",
    how_it_works: "كيف يعمل",
    simple_process: "عملية بسيطة",
    how_it_works_desc: "ثلاث خطوات بسيطة للبدء",
    step: "خطوة",
    create_account: "إنشاء حساب",
    create_account_desc: "إنشاء حساب جديد ومجاني - تحتاج فقط الاسم والبريد الإلكتروني.",
    login_verify: "تسجيل الدخول والتحقق",
    login_verify_desc: "أدخل بياناتك (اسم المستخدم وكلمة المرور) للدخول إلى النظام.",
    access_dashboard: "الوصول إلى لوحة التحكم",
    access_dashboard_desc: "احصل على لوحة التحكم الخاصة بك مع جميع الخدمات في مكان واحد.",
    trusted_by_thousands: "موثوق به من الآلاف",
    trusted_desc: "عملاؤنا راضون عن هذا النظام",
    ready_to_get_started: "مستعد للبدء؟",
    ready_desc: "ابدأ إدارة أموالك اليوم - حساب مجاني، بدون أي رسوم.",
    create_free_account: "إنشاء حساب مجاني",
    quick_links: "روابط سريعة",
    account_link: "الحساب",
    create_account_link: "إنشاء حساب",
    forgot_password_link: "نسيت كلمة المرور",
    copyright: "© 2026 بنك غابيلي. جميع الحقوق محفوظة.",
    testimonial_1: "هذا النظام سهل جداً وفعال. أدير أعمالي بسرعة.",
    testimonial_2: "أحب كيف أن النظام سهل. يمكنني الوصول إلى حسابي من أي مكان.",
    testimonial_3: "خدمات الموظفين ممتازة. أدير العملاء بسهولة.",
    // Additional descriptive texts
    account_management_full: "إدارة حساباتك بسهولة - إنشاء حسابات جديدة، عرض الأرصدة، التبديل بين الأنواع المختلفة، وحفظ جميع أموالك في مكان آمن واحد.",
    transactions_full: "المعاملات المالية السريعة - إيداع، سحب، تحويل، عرض سجل جميع المعاملات، وتتبع جميع أموالك.",
    transfers_full: "إرسال الأموال بسرعة وأمان - محلياً ودولياً، التحويل إلى بنوك أخرى، إضافة الأموال الإلكترونية، وتتبع جميع التحويلات.",
    loans_full: "خدمات القروض - التقدم بطلب لقرض جديد، عرض حالة القرض، السداد، وتتبع الفائدة وفترة القرض.",
    reports_full: "التقارير والتحليلات - عرض البيانات المهمة، التقارير اليومية، ملخصات العملاء، وتتبع أعمالك.",
    security_full: "الأمان المالي - نظام 2FA، مفاتيح مشفرة، نسخ احتياطي للبيانات، وحماية معلوماتك.",
    employee_management_full: "إدارة الموظفين - إضافة موظفين جدد، تعديل البيانات، عرض أعمالهم، وإدارة الصلاحيات والرواتب.",
    customer_service_full: "خدمة العملاء - الاتصال بالدعم، عرض الطلبات، إضافة عملاء جدد، وإدارة علاقات العمل بسهولة.",
    // Roles
    business_owner: "صاحب الأعمال",
    customer_role: "عميل",
    employee_role: "موظف",
    // Account Registration
    mother_name: "اسم الأم الكامل",
    id_card_image: "صورة بطاقة الهوية",
    account_type: "نوع الحساب",
    savings_account: "حساب التوفير",
    current_account: "حساب جاري",
    fixed_deposit: "وديعة ثابتة",
    purpose: "الغرض",
    create_account_for_customer: "إنشاء حساب للعميل",
    create_account_desc: "إنشاء حساب بنكي جديد للعميل",
    search_customer: "البحث عن عميل",
    search_customer_placeholder: "بحث بالاسم أو اسم المستخدم أو البريد الإلكتروني...",
    select_customer: "اختر عميلاً",
    account_created_success: "تم إنشاء الحساب بنجاح",
    add_new_account: "إضافة حساب جديد",
    existing_customer: "عميل موجود",
    new_customer: "عميل جديد",
    create_account: "إنشاء حساب",
    change: "تغيير",
    full_name_placeholder: "أدخل الاسم الكامل",
    username_placeholder: "اختر اسم المستخدم",
    email_placeholder: "أدخل البريد الإلكتروني",
    phone_placeholder: "أدخل رقم الهاتف",
    password_placeholder: "أدخل كلمة المرور",
    confirm_password_placeholder: "تأكيد كلمة المرور",
    mother_name_placeholder: "أدخل اسم الأم الكامل",
    upload_id_card: "رفع صورة بطاقة الهوية (الحد الأقصى 5 ميجا)",
    purpose_placeholder: "غرض هذا الحساب...",
    // Months
    jan: "يناير",
    feb: "فبراير",
    mar: "مارس",
    apr: "أبريل",
    may: "مايو",
    jun: "يونيو",
    jul: "يوليو",
    aug: "أغسطس",
    sep: "سبتمبر",
    oct: "أكتوبر",
    nov: "نوفمبر",
    dec: "ديسمبر",
    ssl_256: "256-bit SSL",
    // Top Users
    top_users: "المستخدمون الأعلى نشاطاً",
    most_active_users: "المستخدمون الأكثر نشاطاً",
    most_active_logins: "الأكثر نشاطاً (تسجيل الدخول)",
    most_active_transactions: "الأكثر نشاطاً (المعاملات)",
    employee_performance: "أداء الموظفين",
    login_count: "عدد تسجيلات الدخول",
    transaction_count: "عدد المعاملات",
    total_processed: "إجمالي المعالجات",
    active_this_week: "نشط هذا الأسبوع",
    active_this_month: "نشط هذا الشهر",
    user_rankings: "ترتيب المستخدمين",
    activity_summary: "ملخص النشاط",
    top_accounts: "الحسابات الأعلى",
    active_users: "المستخدمون النشطون",
    logins_this_week: "تسجيلات الدخول هذا الأسبوع",
    logins_this_month: "تسجيلات الدخول هذا الشهر",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const stored = localStorage.getItem("language") as Language;
    if (stored && translations[stored]) {
      setLanguageState(stored);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
